language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12
  - 1.13
  - 1.14
  - master

cache:
  directories:
    - vendor/

install:
  - make godeps
  - make dependencies

script:
  - make client
  - make server
  - travis_retry make test
  - travis_retry make cover
