name: check-continentmap

on:
  schedule:
    - cron: "0 2 * * SUN"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0

    - name: Check continentmap
      run: make check-continentmap
